# Generated by Django 4.2.1 on 2023-06-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_app', '0003_patient_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
