print("Welcome to the Band Name Generator. \nWhat's name of the city you grew up in?")
city = input()
print("What's your pet name?")
petName = input()
print("Your band name could be: " + city + " " + petName)